version: '3.7'
services:
  redis:
    image: redis:5-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  mongo:
    image: bitnami/mongodb:4.2.3
  api:
    image: api:latest
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sample
      - REDIS_URI=redis://redis:6379
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongo
      - redis
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    ports:
      - '80:80'
