version: '3.7'
services:
  mongo:
    image: bitnami/mongodb:4.2.3
  api:
    image: api:latest
    ports:
      - 80:5000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/sample
      - PORT=5000
    depends_on:
      - mongo
